// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zenkoi.DAL.EF;

#nullable disable

namespace Zenkoi.DAL.Migrations
{
    [DbContext(typeof(ZenKoiContext))]
    [Migration("20251029135304_ChangeTypeOfImageVideoInPacketFish")]
    partial class ChangeTypeOfImageVideoInPacketFish
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("ApplicationUsers", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("TotalAreaSQM")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Areas", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.BreedingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FemaleKoiId")
                        .HasColumnType("int");

                    b.Property<double?>("FertilizationRate")
                        .HasColumnType("float");

                    b.Property<double?>("HatchingRate")
                        .HasColumnType("float");

                    b.Property<int>("MaleKoiId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PondId")
                        .HasColumnType("int");

                    b.Property<int?>("PondId1")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("SurvivalRate")
                        .HasColumnType("float");

                    b.Property<int?>("TotalEggs")
                        .HasColumnType("int");

                    b.Property<int?>("TotalFishQualified")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPackage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FemaleKoiId");

                    b.HasIndex("MaleKoiId");

                    b.HasIndex("PondId");

                    b.HasIndex("PondId1");

                    b.ToTable("BreedingProcesses", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("AddedAt");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartId");

                    b.Property<int?>("KoiFishId")
                        .HasColumnType("int")
                        .HasColumnName("KoiFishId");

                    b.Property<int?>("PacketFishId")
                        .HasColumnType("int")
                        .HasColumnName("PacketFishId");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("KoiFishId");

                    b.HasIndex("PacketFishId");

                    b.ToTable("CartItems", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ClassificationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassificationStageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CullQualifiedCount")
                        .HasColumnType("int");

                    b.Property<int?>("HighQualifiedCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PondQualifiedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ShowQualifiedCount")
                        .HasColumnType("int");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationStageId");

                    b.ToTable("ClassificationRecords", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ClassificationStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedingProcessId")
                        .HasColumnType("int");

                    b.Property<int?>("CullQualifiedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HighQualifiedCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PondQualifiedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ShowQualifiedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedingProcessId")
                        .IsUnique();

                    b.ToTable("ClassificationStages", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TotalOrders")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.EggBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedingProcessId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FertilizationRate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("HatchingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PondId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SpawnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalHatchedEggs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedingProcessId")
                        .IsUnique();

                    b.HasIndex("PondId");

                    b.ToTable("EggBatches", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.FryFish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BreedingProcessId")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentSurvivalRate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InitialCount")
                        .HasColumnType("int");

                    b.Property<int?>("PondId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BreedingProcessId")
                        .IsUnique();

                    b.HasIndex("PondId");

                    b.ToTable("FryFishes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.FrySurvivalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountAlive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DayNumber")
                        .HasColumnType("datetime2");

                    b.Property<int>("FryFishId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<double?>("SurvivalRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FryFishId");

                    b.ToTable("FrySurvivalRecords", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IncidentTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IncidentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentTypeId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("Incidents", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.IncidentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectsBreeding")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("RequiresQuarantine")
                        .HasColumnType("bit");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IncidentTypes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.IncubationDailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DayNumber")
                        .HasColumnType("datetime2");

                    b.Property<int>("EggBatchId")
                        .HasColumnType("int");

                    b.Property<int?>("HatchedEggs")
                        .HasColumnType("int");

                    b.Property<int?>("HealthyEggs")
                        .HasColumnType("int");

                    b.Property<int?>("RottenEggs")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EggBatchId");

                    b.ToTable("IncubationDailyRecords", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.KoiFish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BodyShape")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BreedingProcessId")
                        .HasColumnType("int");

                    b.Property<string>("ColorPattern")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Origin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PondId")
                        .HasColumnType("int");

                    b.Property<string>("RFID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SaleStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("NotForSale");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VarietyId")
                        .HasColumnType("int");

                    b.Property<string>("Videos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BreedingProcessId");

                    b.HasIndex("PondId");

                    b.HasIndex("RFID")
                        .IsUnique();

                    b.HasIndex("VarietyId");

                    b.ToTable("KoiFishes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.KoiIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AffectedFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AffectedStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIsolated")
                        .HasColumnType("bit");

                    b.Property<int>("KoiFishId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequiresTreatment")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificSymptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TreatmentNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("KoiFishId");

                    b.ToTable("KoiIncidents", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PromotionId");

                    b.ToTable("Orders", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KoiFishId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("PacketFishId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KoiFishId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PacketFishId");

                    b.ToTable("OrderDetails", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_OrderDetail_KoiOrPacket", "(KoiFishId IS NOT NULL AND PacketFishId IS NULL) OR (KoiFishId IS NULL AND PacketFishId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PacketFish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgeMonths")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.PrimitiveCollection<string>("Images")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Videos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PacketFishes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PaymentInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ResponseData")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActualOrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Pond", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CapacityLiters")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("DepthMeters")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("LengthMeters")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PondName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PondStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("PondTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WidthMeters")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("PondName");

                    b.HasIndex("PondTypeId");

                    b.ToTable("Ponds", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PondIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectiveActions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EnvironmentalChanges")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("FishDiedCount")
                        .HasColumnType("int");

                    b.Property<string>("ImpactLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PondId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("RequiresWaterChange")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("PondId");

                    b.ToTable("PondIncidents", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PondPacketFish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PacketFishId")
                        .HasColumnType("int");

                    b.Property<int>("PondId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacketFishId");

                    b.HasIndex("PondId", "PacketFishId")
                        .IsUnique();

                    b.ToTable("PondPacketFishes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PondType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RecommendedCapacity")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("PondTypes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumOrderAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ValidFrom");

                    b.HasIndex("ValidTo");

                    b.ToTable("Promotions", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.TaskTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsRecurring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("PondId")
                        .HasColumnType("int");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("PondId");

                    b.HasIndex("ScheduledAt");

                    b.ToTable("TaskTemplates", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<string>("AvatarURL")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("UserDetails", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Variety", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Characteristic")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VarietyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("VarietyName")
                        .IsUnique();

                    b.ToTable("Varieties", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.VarietyPacketFish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("PacketFishId")
                        .HasColumnType("int");

                    b.Property<int>("VarietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacketFishId");

                    b.HasIndex("VarietyId", "PacketFishId")
                        .IsUnique();

                    b.ToTable("VarietyPacketFishes", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WaterAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MeasuredValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PondId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsResolved");

                    b.HasIndex("PondId");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("WaterAlerts", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WaterParameterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AmmoniaLevel")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("CarbonHardness")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("NitrateLevel")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("NitriteLevel")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("OxygenLevel")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("PHLevel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PondId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("RecordedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("TotalChlorines")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Turbidity")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("WaterLevelMeters")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("PondId");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("RecordedByUserId");

                    b.ToTable("WaterParameterRecords", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WaterParameterThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PondTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterName");

                    b.HasIndex("PondTypeId");

                    b.ToTable("WaterParameterThresholds", "dbo");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ManagerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeSpan(0, 0, 0, 0, 0));

                    b.Property<int>("TaskTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TaskTemplateId");

                    b.HasIndex("WorkDate");

                    b.ToTable("WorkSchedules", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.BreedingProcess", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.KoiFish", "FemaleKoi")
                        .WithMany()
                        .HasForeignKey("FemaleKoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.KoiFish", "MaleKoi")
                        .WithMany()
                        .HasForeignKey("MaleKoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany()
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zenkoi.DAL.Entities.Pond", null)
                        .WithMany("BreedingProcesses")
                        .HasForeignKey("PondId1");

                    b.Navigation("FemaleKoi");

                    b.Navigation("MaleKoi");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Cart", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Customer", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("Zenkoi.DAL.Entities.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.CartItem", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.KoiFish", "KoiFish")
                        .WithMany()
                        .HasForeignKey("KoiFishId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zenkoi.DAL.Entities.PacketFish", "PacketFish")
                        .WithMany()
                        .HasForeignKey("PacketFishId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cart");

                    b.Navigation("KoiFish");

                    b.Navigation("PacketFish");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ClassificationRecord", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ClassificationStage", "ClassificationStage")
                        .WithMany("ClassificationRecords")
                        .HasForeignKey("ClassificationStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassificationStage");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ClassificationStage", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.BreedingProcess", "BreedingProcess")
                        .WithOne("ClassificationStage")
                        .HasForeignKey("Zenkoi.DAL.Entities.ClassificationStage", "BreedingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreedingProcess");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Customer", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("Zenkoi.DAL.Entities.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.EggBatch", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.BreedingProcess", "BreedingProcess")
                        .WithOne("Batch")
                        .HasForeignKey("Zenkoi.DAL.Entities.EggBatch", "BreedingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Pond", null)
                        .WithMany("EggBatches")
                        .HasForeignKey("PondId");

                    b.Navigation("BreedingProcess");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.FryFish", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.BreedingProcess", "BreedingProcess")
                        .WithOne("FryFish")
                        .HasForeignKey("Zenkoi.DAL.Entities.FryFish", "BreedingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Pond", null)
                        .WithMany("FryFishes")
                        .HasForeignKey("PondId");

                    b.Navigation("BreedingProcess");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.FrySurvivalRecord", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.FryFish", "FryFish")
                        .WithMany("FrySurvivalRecords")
                        .HasForeignKey("FryFishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FryFish");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Incident", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.IncidentType", "IncidentType")
                        .WithMany("Incidents")
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IncidentType");

                    b.Navigation("ReportedBy");

                    b.Navigation("ResolvedBy");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.IncubationDailyRecord", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.EggBatch", "EggBatch")
                        .WithMany("IncubationDailyRecords")
                        .HasForeignKey("EggBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EggBatch");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.KoiFish", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.BreedingProcess", "BreedingProcess")
                        .WithMany("KoiFishes")
                        .HasForeignKey("BreedingProcessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany("KoiFishes")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Variety", "Variety")
                        .WithMany("KoiFishes")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BreedingProcess");

                    b.Navigation("Pond");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.KoiIncident", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Incident", "Incident")
                        .WithMany("KoiIncidents")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.KoiFish", "KoiFish")
                        .WithMany("KoiIncidents")
                        .HasForeignKey("KoiFishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("KoiFish");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Order", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Promotion", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.KoiFish", "KoiFish")
                        .WithMany("OrderDetails")
                        .HasForeignKey("KoiFishId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zenkoi.DAL.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.PacketFish", "PacketFish")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PacketFishId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KoiFish");

                    b.Navigation("Order");

                    b.Navigation("PacketFish");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Payment", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Zenkoi.DAL.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Order", "ActualOrder")
                        .WithMany()
                        .HasForeignKey("ActualOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Pond", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Area", "Area")
                        .WithMany("Ponds")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.PondType", "PondType")
                        .WithMany("Ponds")
                        .HasForeignKey("PondTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("PondType");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PondIncident", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Incident", "Incident")
                        .WithMany("PondIncidents")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany("PondIncidents")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PondPacketFish", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.PacketFish", "PacketFish")
                        .WithMany("PondPacketFishes")
                        .HasForeignKey("PacketFishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany("PondPacketFishes")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PacketFish");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.TaskTemplate", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany("Tasks")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedTo");

                    b.Navigation("Pond");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.UserDetail", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("Zenkoi.DAL.Entities.UserDetail", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.VarietyPacketFish", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.PacketFish", "PacketFish")
                        .WithMany("VarietyPacketFishes")
                        .HasForeignKey("PacketFishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.Variety", "Variety")
                        .WithMany("VarietyPacketFishes")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PacketFish");

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WaterAlert", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany()
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pond");

                    b.Navigation("ResolvedBy");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WaterParameterRecord", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.Pond", "Pond")
                        .WithMany("WaterParameters")
                        .HasForeignKey("PondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "RecordedBy")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pond");

                    b.Navigation("RecordedBy");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WaterParameterThreshold", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.PondType", "PondType")
                        .WithMany("WaterParameterThresholds")
                        .HasForeignKey("PondTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PondType");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.ApplicationUser", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zenkoi.DAL.Entities.TaskTemplate", "TaskTemplate")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Staff");

                    b.Navigation("TaskTemplate");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Area", b =>
                {
                    b.Navigation("Ponds");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.BreedingProcess", b =>
                {
                    b.Navigation("Batch");

                    b.Navigation("ClassificationStage");

                    b.Navigation("FryFish");

                    b.Navigation("KoiFishes");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.ClassificationStage", b =>
                {
                    b.Navigation("ClassificationRecords");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.EggBatch", b =>
                {
                    b.Navigation("IncubationDailyRecords");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.FryFish", b =>
                {
                    b.Navigation("FrySurvivalRecords");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Incident", b =>
                {
                    b.Navigation("KoiIncidents");

                    b.Navigation("PondIncidents");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.IncidentType", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.KoiFish", b =>
                {
                    b.Navigation("KoiIncidents");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PacketFish", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PondPacketFishes");

                    b.Navigation("VarietyPacketFishes");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Pond", b =>
                {
                    b.Navigation("BreedingProcesses");

                    b.Navigation("EggBatches");

                    b.Navigation("FryFishes");

                    b.Navigation("KoiFishes");

                    b.Navigation("PondIncidents");

                    b.Navigation("PondPacketFishes");

                    b.Navigation("Tasks");

                    b.Navigation("WaterParameters");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.PondType", b =>
                {
                    b.Navigation("Ponds");

                    b.Navigation("WaterParameterThresholds");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.TaskTemplate", b =>
                {
                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Zenkoi.DAL.Entities.Variety", b =>
                {
                    b.Navigation("KoiFishes");

                    b.Navigation("VarietyPacketFishes");
                });
#pragma warning restore 612, 618
        }
    }
}
